export const ADDPOKEONTOTEAM = "ADDPOKEMONTOTEAM";
export const CREATEPOKEMON = 'CREATEPOKEMON';
export const CREATETEAM = 'CREATETEAM';
export const DELETEPOKEMON = 'CREATEPOKEMON';
export const DELETETEAM = 'DELETEPOKEMON';
export const REMOVEPOKEMONFROMTEAM = 'REMOVEPOKEMONFROMTEAM';